# ls-rescue
Download this tool, save your ls before and after your mistake to 2 separate files, and run 
```
python3 ls-rescue.py ls1_file ls2_file
```
.
You'll see what changed.
